Portfolio: setup and mobile version skeleton
MmakolaMC/Portfolio-setup-and-mobile-version-skeleton pull request #1
Opened 2022-04-21 18:10 UTC by MmakolaMC

Added the workflows folder.

2022-04-23 18:09 UTC, youmari requested changes
Hi @MmakolaMC, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that 

- [ ] doesn't have a descriptive short summary that tells what you've done in details 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-04-23 18:16 UTC, MmakolaMC commented
@youmari you mean in the pull request description?

2022-04-23 19:32 UTC, gtekle requested changes
Hi @MmakolaMC :wave:, 

Good job so far! :clap: :clap: 
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost-there-01](https://user-images.githubusercontent.com/44057863/164943566-1c5341d7-e4b2-4e15-8b47-a942d086f3e2.gif)


## Highlights
:heavy_check_mark: Cleand and organized code
:heavy_check_mark: Linters setup correctly
:heavy_check_mark: Good use of GitHub flow

## Required Changes ♻️
_Check the comments under the review._

- [ ] You should add the decorator background image for the headline section as in the Figma design. Please take a look in the snapshot at the bottom right corner.[How to add background-images](https://www.w3schools.com/cssref/pr_background-image.asp)
![decorator-bg-image-figma](https://user-images.githubusercontent.com/44057863/164943508-edccd521-13f1-4bf5-9161-f8c1e815c9b2.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-23 19:32 UTC, gtekle commented on index.html
> +                <p class="one">I'm Clive Glad to see you!</p>
- [ ] You should use an `<h1>` heading tag for the `I am Clive` part and any of `<h2> ... <h6>` heading tags for the `Glad to see you!` part. The reason behind is to use a more semantically meaningful HTML element. Using HTML semantic tags helps for SEO, accessibility, etc. The reason why we need to use `<h1>` for the first part is because this is the most important heading in your portfolio website.
- [ ] You should use the `Crete Round` font-family,  `400 font-weight`, `56px font-size` and `#FF6B00 font-color` for both parts (`I am Clive` and `Glad to see you!`)

2022-04-23 19:32 UTC, gtekle commented on index.html
> +                <p class="two">I’am a Software Developer</p>
- [ ] You should use `Roboto` font-family, `700 font-weight`, `24px font-size` and `#FFF5E1 font-color` for this paragraph.

2022-04-23 19:32 UTC, gtekle commented on index.html
> +                    don’t hestiate to contact me.</p>
- [ ] You should use `Poppins` font-family, `400 font-weight`, `16px font-size` for this paragraph as in the Figma design.

2022-04-23 19:32 UTC, gtekle commented on index.html
> +                </ul>
- [ ] Great job in implementing this section well. You should increase the font-size of the fa-icons to 20px to make look in the Figma design.

2022-04-23 21:55 UTC, youmari commented
> @youmari you mean in the pull request description?
Yeah

2022-04-26 11:44 UTC, zieeco requested changes
Hi @MmakolaMC 


Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the changes, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._


<img src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>


## Optional suggestions
_Check the comments under the review._

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-26 11:44 UTC, zieeco commented on index.html
> +                <img src="image/Union.png" class="menu" alt="hambuger menu">
- [ ] **[REQUIRED CHANGES]**

- Great job on implementing the changes required by the previous reviewers, however, you omitted to add your hamburger icon here. please kindly add it..
- Also, you've incorrectly specified the file path in your src. instead do this `<img src="./image/Union.png">`

2022-04-26 11:44 UTC, zieeco commented on style.css
> +  background-image: url('image/Illustration.png');
- [ ] **[REQUIRED CHANGES]**

- [ ] Also, you've incorrectly specified the file path in the background image. You can do this `background-image: url(./image/Illustration-header.png)` to fix it.

> **[OPTIONAL]** I think the background-image should be in you `<section class="content">` and not in the `<main>` . Please, kindly fix this also in your design



> || **YOUR DESIGN** || **FIGMA DESIGN** ||
> |-|---------|-|---------|-|
> || ![design](https://user-images.githubusercontent.com/59397159/165292492-9b5c7c1f-ca6a-4df4-9d19-9cebd7b7a93a.png) || ![design2](https://user-images.githubusercontent.com/59397159/165292609-f61c527f-8f45-42d3-a6be-df55f7eeea23.png) ||

2022-04-26 12:16 UTC, MmakolaMC commented on style.css
> +  background-image: url('image/Illustration.png');
@zieeco the way I set up my section and my contact information won't allow the picture to be set at the bottom right corner of the page. my main div that contains the everything in the page besides the header is the main.

2022-04-26 12:25 UTC, AnselemOdims approved these changes
### Hi  @MmakolaMC 🙋‍♀️, 
Good job in making the required changes 👏 

# STATUS APPROVED ✔
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Use the tag @AnselemOdims for a quicker reply


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-26 12:34 UTC, merged